# Generated by Django 4.1 on 2022-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_no', models.IntegerField(max_length=50)),
                ('account_balance', models.FloatField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
